#ifndef DETECT_ANOMALY_H
#define DETECT_ANOMALY_H

/* Auto-generated by tinyML notebook — DO NOT EDIT MANUALLY */
/* Model: DecisionTreeClassifier trained on single-phase (V, I) fault data */

#include <string.h>
static void _anomaly_score(float * input, float * output) {
    float var0[2];
    if (input[1] <= 72.90320587158203) {
        if (input[0] <= 0.5086576044559479) {
            if (input[1] <= 19.780384063720703) {
                memcpy(var0, (float[]){0.15139442231075698, 0.848605577689243}, 2 * sizeof(float));
            } else {
                memcpy(var0, (float[]){0.812484076433121, 0.187515923566879}, 2 * sizeof(float));
            }
        } else {
            if (input[0] <= 0.5185004472732544) {
                memcpy(var0, (float[]){0.9727272727272728, 0.02727272727272727}, 2 * sizeof(float));
            } else {
                memcpy(var0, (float[]){1.0, 0.0}, 2 * sizeof(float));
            }
        }
    } else {
        if (input[1] <= 83.65932083129883) {
            if (input[0] <= 0.07334069348871708) {
                memcpy(var0, (float[]){0.0, 1.0}, 2 * sizeof(float));
            } else {
                memcpy(var0, (float[]){0.6190476190476191, 0.38095238095238093}, 2 * sizeof(float));
            }
        } else {
            if (input[1] <= 90.39396667480469) {
                memcpy(var0, (float[]){0.08333333333333333, 0.9166666666666666}, 2 * sizeof(float));
            } else {
                memcpy(var0, (float[]){0.0005875440658049354, 0.999412455934195}, 2 * sizeof(float));
            }
        }
    }
    memcpy(output, var0, 2 * sizeof(float));
}

/* Public API — call this from the sensor firmware */
/* v = absolute single-phase voltage, i = absolute single-phase current */
/* returns: 1 = anomaly detected, 0 = normal                            */
static int detect_anomaly(float v, float i) {
    float input[2] = {v, i};
    float output[2];
    _anomaly_score(input, output);
    return output[1] > 0.5f ? 1 : 0;
}

#endif /* DETECT_ANOMALY_H */
